apiVersion: v1
data:
  accounts.admin: apiKey, login
  policy.csv: |
    g, argo-account, role:admin
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"accounts.admin":"apiKey, login","policy.csv":"g, argo-account, role:admin\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-08-29T18:26:14Z","name":"argocd-rbac-cm","namespace":"argocd","resourceVersion":"58640","uid":"9972a2c3-e222-4845-be56-82ab3a25fea3"}}
  name: argocd-rbac-cm
  namespace: argocd
