name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set build version
        id: version
        run: echo "version=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Print build version
        run: echo "Build version is ${{ env.version }}"

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t bickyraj/demo-java-app:${{ github.sha }} .
          docker push bickyraj/demo-java-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions[bot]'
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Update Kubernetes manifests
        run: |
          sed -i 's|image: bickyraj/demo-java-app:PLACEHOLDER|image: bickyraj/demo-java-app:${{ github.sha }}|' argocd/deployment/demo-java-app-deployment.yaml
          git config --global user.email "bickyrajkayastha@gmail.com"
          git config --global user.name "bickyraj"
          git add argocd/deployment/demo-java-app-deployment.yaml
          git commit -m "Update image version to ${{ github.sha }} [skip ci]"
          git push origin main

  sync:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Install Argo CD CLI
        run: curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64 && chmod +x /usr/local/bin/argocd

      - name: Sync Argo CD Application
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username ${{ secrets.ARGOCD_USERNAME }} --password ${{ secrets.ARGOCD_TOKEN }} --insecure
          argocd app sync java-app
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}