name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        run: |
          docker build -t bickyraj/demo-java-app:${{ github.sha }} .
          docker push bickyraj/java-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Update Kubernetes manifests
        run: |
          sed -i 's|image: bickyraj/demo-java-app:.*|image: bickyraj/demo-java-app:${{ github.sha }}|' argocd/deployment/demo-java-app-deployment.yaml
          git config --global user.email "bickyrajkayastha@gmail.com"
          git config --global user.name "bickyraj"
          git add argocd/deployment/demo-java-app-deployment.yaml
          git commit -m "Update image version to ${{ github.sha }}"
          git push origin main

  sync:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Sync Argo CD Application
        run: |
          argocd login ${{ secrets.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_TOKEN }} --insecure
          argocd app sync java-app
        env:
          ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
          ARGOCD_TOKEN: ${{ secrets.ARGOCD_TOKEN }}